#!/usr/bin/env python3
"""
cpcap.py

Task 5 – Copy / replicate captions from original images to their augmented
counterparts generated by augment.py.

Ported from cpcap.py with a clean function-level API.
"""

from __future__ import annotations

import logging
import shutil
from pathlib import Path

logger = logging.getLogger(__name__)

VALID_IMAGE_EXTS: set[str] = {".jpg", ".jpeg", ".png", ".webp", ".bmp", ".tiff", ".tif"}


def infer_original_stem(augmented_stem: str) -> str:
    """Strip ``_aug<digits>`` or ``_orig`` suffix to recover the original stem.

    Examples::

        "photo1_aug000" -> "photo1"
        "photo1_orig"   -> "photo1"
        "photo1"        -> "photo1"   (unchanged)
    """
    if augmented_stem.endswith("_orig"):
        return augmented_stem[: -len("_orig")]
    if "_aug" in augmented_stem:
        idx = augmented_stem.rfind("_aug")
        return augmented_stem[:idx]
    return augmented_stem


def copy_captions(
    source_dir: Path,
    aug_dir: Path,
    caption_ext: str = ".txt",
    dry_run: bool = False,
    skip_existing: bool = True,
) -> dict[str, int]:
    """Copy caption files from *source_dir* to matching images in *aug_dir*.

    For each augmented image in *aug_dir* the function:
    1. Infers the original stem (strips ``_aug<N>`` / ``_orig``).
    2. Looks up the corresponding caption in *source_dir*.
    3. Copies it next to the augmented image with the new stem.

    Args:
        source_dir:    Directory containing original images and their captions.
        aug_dir:       Directory containing augmented images.
        caption_ext:   Caption file extension (default: ``".txt"``).
        dry_run:       If True, report what would be done without writing files.
        skip_existing: Skip augmented images whose caption already exists.

    Returns:
        Summary dict with keys ``created``, ``skipped_existing``,
        ``skipped_no_source``.
    """
    source_dir = source_dir.resolve()
    aug_dir = aug_dir.resolve()

    if not source_dir.is_dir():
        raise FileNotFoundError(f"Source dir does not exist: {source_dir}")
    if not aug_dir.is_dir():
        raise FileNotFoundError(f"Aug dir does not exist: {aug_dir}")

    aug_images = [
        p
        for p in aug_dir.rglob("*")
        if p.is_file() and p.suffix.lower() in VALID_IMAGE_EXTS
    ]

    if not aug_images:
        logger.warning("No images found in %s", aug_dir)
        return {"created": 0, "skipped_existing": 0, "skipped_no_source": 0}

    created = 0
    skipped_existing = 0
    skipped_no_source = 0

    for img_path in aug_images:
        rel_dir = img_path.parent.relative_to(aug_dir)
        orig_stem = infer_original_stem(img_path.stem)
        orig_caption = source_dir / rel_dir / f"{orig_stem}{caption_ext}"

        if not orig_caption.is_file():
            logger.debug("No source caption for %s (expected %s)", img_path.name, orig_caption)
            skipped_no_source += 1
            continue

        target_caption = img_path.with_suffix(caption_ext)

        if skip_existing and target_caption.exists():
            skipped_existing += 1
            continue

        if not dry_run:
            target_caption.parent.mkdir(parents=True, exist_ok=True)
            shutil.copy2(orig_caption, target_caption)

        logger.info(
            "%sCopied: %s → %s",
            "[DRY-RUN] " if dry_run else "",
            orig_caption.name,
            target_caption,
        )
        created += 1

    return {
        "created": created,
        "skipped_existing": skipped_existing,
        "skipped_no_source": skipped_no_source,
    }
